# Generated by Django 6.0.5 on 2026-06-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iso_code', models.CharField(max_length=5, unique=True)),
                ('phone_code', models.CharField(max_length=10)),
                ('mobile_prefix', models.CharField(blank=True, max_length=5, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
