# Generated by Django 5.2.7 on 2025-10-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_mobile_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency_symbol',
            field=models.CharField(default='$', max_length=5),
        ),
    ]
