# Generated by Django 6.0.5 on 2026-06-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20260601_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['ordering'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('VENTA', 'Venta Directa'), ('ARRIENDO', 'Arriendo Temporal')], default='VENTA', max_length=10, verbose_name='Modalidad del producto/servicio'),
        ),
    ]
