# Generated by Django 5.2.7 on 2025-11-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_price'),
        ('vendor', '0007_preference_profile_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preferences',
            field=models.ManyToManyField(blank=True, to='vendor.preference'),
        ),
    ]
