# Generated by Django 5.2.7 on 2025-12-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_ingredientcategory_ingredient_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='products', through='product.ProductIngredient', to='product.ingredient', verbose_name='Ingredientes'),
        ),
    ]
