# Generated by Django 5.2.7 on 2025-11-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionlog',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
