# Generated by Django 5.2.7 on 2025-11-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_useractionlog_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionlog',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
