# Generated by Django 5.2.7 on 2025-11-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_useractionlog_extra_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractionlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='useractionlog',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
