# Generated by Django 5.2.7 on 2025-12-15 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('all', 'Todos'), ('comuna', 'Por comuna'), ('vendor', 'Vendedor específico')], max_length=20)),
                ('comuna', models.CharField(blank=True, max_length=120, null=True)),
                ('vendor_id', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='admin_vendor_messages/')),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_message_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
