# Generated by Django 5.2.7 on 2025-11-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapi', '0002_logintoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcart',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de teléfono del usuario (wa_id)'),
        ),
    ]
