# Generated by Django 5.2.7 on 2025-11-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_paid_order_status_alter_order_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='original_price',
            field=models.IntegerField(default=0),
        ),
    ]
