# Generated by Django 5.2.7 on 2025-11-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderitem_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada'), ('accepted', 'Aceptada'), ('preparing', 'Preparando'), ('ready', 'Lista para retiro'), ('delivered', 'Entregada'), ('cancelled', 'Cancelada')], default='pending', max_length=20),
        ),
    ]
